### ISSUE TITLE
无法同步, 能帮忙解决一下吗

### ISSUE THREAD

**Issue by wfwf1990** [shynome/zentao-ldap#1]
![图片](https://user-images.githubusercontent.com/31684764/58681598-a6069a00-839f-11e9-8772-a6ec55ee9dfc.png)
![图片](https://user-images.githubusercontent.com/31684764/58681608-b3bc1f80-839f-11e9-8811-8ed9f690b713.png)

ldap日志
![图片](https://user-images.githubusercontent.com/31684764/58681615-bae32d80-839f-11e9-9ce7-10d06a528a15.png)

**Comment by wfwf1990** [comment]
@shynome

**Comment by shynome** [comment]
filter 填下: `(objectclass=inetOrgPerson)` , 这个是只允许 entry 为 inetOrgPerson 的过滤

**Comment by shynome** [comment]
所有字段都应该要填的

**Comment by wfwf1990** [comment]
![image](https://user-images.githubusercontent.com/31684764/58697198-b7fe3200-83cb-11e9-887c-9595bfaa460b.png)
厉害了  大神
