### ISSUE TITLE
关于ldap自动同步问题

### ISSUE THREAD

**Issue by yeguhe** [shynome/zentao-ldap#5]
大佬好：
       请教如何实现在配置好ldap信息后，pms系统每半小时自动发起向ldap服务器全量同步一次ldap用户信息，现在的效果是必须在配置好ldap信息后手动同步，才能把ldap系统里的用户拉取到本地，负面效果是ldap系统里新增用户后不能登陆pms系统，人员离职后，删除ldap系统里的账户，离职人员账户仍能够登陆pms. 感谢！

**Comment by shynome** [comment]
只能手动同步新增用户是预期的，有人提过在登录的时候同步ldap用户，但我不是这个软件的开发者只是把它修正到新版禅道可用，不清楚这个软件的逻辑所以选择不添加这个功能
删除ldap系统里的用户用户不可再登录，但现有session在失效前仍可使用该系统，等待现有session失效即可

**Comment by yeguhe** [comment]
了解了，感谢大佬!!!
